### ISSUE TITLE
Comments in gsp views may not have the right color

### ISSUE THREAD

**Issue by battaglr** [mathifonseca/atom-grails#2]
Is this the intended look for comments in gsp views?

> ![comments](https://cloud.githubusercontent.com/assets/1921409/15478487/defae7b8-20f0-11e6-9152-e35730e47d6b.png)

**Comment by mathifonseca** [comment]
No 😃. Thanks for reporting it, I never noticed it because the comment keyboard shortcut ( <kbd>⌘</kbd> + <kbd>/</kbd> ) generates HTML comments. I'll fix it and let you know.

**Comment by mathifonseca** [comment]
Fixed in commit 67f2e0e 👍. Please update to version 1.0.0 and let me know if you run into any more issues. I also added many more snippets in this version.

**Comment by battaglr** [comment]
Awesome! I'll update and let you know if I find any issue.

Thank you for fixing this. :+1:
