### ISSUE TITLE
<% @page import="..." %> breaks highlighting until the next JSP end tag

### ISSUE THREAD

**Issue by keigen-shu** [mathifonseca/atom-grails#3]
See screenshot below:
![atomgsp](https://cloud.githubusercontent.com/assets/706074/16075173/69b40f9c-3320-11e6-978e-dbf6766702de.PNG)

**Comment by mathifonseca** [comment]
Do you have the latest version? I've just copied your code and seems pretty different.
![image](https://cloud.githubusercontent.com/assets/4367808/16079991/d0480ca2-32dc-11e6-96cc-c52e4acb672a.png)

**Comment by mathifonseca** [comment]
I've just published a newer version fixing the last percentage symbol coloring in the page import tag. It should be like this now:

![image](https://cloud.githubusercontent.com/assets/4367808/16080459/5c74af4e-32df-11e6-8d90-131a3b68bf45.png)

**Comment by keigen-shu** [comment]
I've updated the package and it works perfect now. Thanks!
